"""add posts, clusters, evidence, risk, predictions, interventions, results, sensors

Revision ID: 5e01b830021e
Revises: 85e2e648d7e8
Create Date: 2026-09-04 23:49:39.739305

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '5e01b830021e'
down_revision: Union[str, Sequence[str], None] = '85e2e648d7e8'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('claim_clusters',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('label', sa.String(length=300), nullable=True),
    sa.Column('summary', sa.Text(), nullable=True),
    sa.Column('representative_claim_id', sa.Integer(), nullable=True),
    sa.Column('size', sa.Integer(), nullable=False),
    sa.Column('cohesion', sa.Float(), nullable=True),
    sa.Column('method_version', sa.String(length=50), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['representative_claim_id'], ['claims.id'], name=op.f('fk_claim_clusters_representative_claim_id_claims'), ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_claim_clusters'))
    )
    op.create_table('interventions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=300), nullable=False),
    sa.Column('intervention_type', sa.String(length=30), nullable=False),
    sa.Column('body', sa.Text(), nullable=True),
    sa.Column('example', sa.Text(), nullable=True),
    sa.Column('question', sa.Text(), nullable=True),
    sa.Column('options', sa.JSON(), nullable=True),
    sa.Column('answer_explanation', sa.Text(), nullable=True),
    sa.Column('target_signal', sa.String(length=100), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.CheckConstraint("intervention_type IN ('prebunk', 'explanation', 'technique_warning', 'quiz')", name=op.f('ck_interventions_intervention_type_valid')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_interventions'))
    )
    op.create_index(op.f('ix_interventions_intervention_type'), 'interventions', ['intervention_type'], unique=False)
    op.create_index(op.f('ix_interventions_target_signal'), 'interventions', ['target_signal'], unique=False)
    op.create_table('evidence',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('claim_id', sa.Integer(), nullable=False),
    sa.Column('source_id', sa.Integer(), nullable=False),
    sa.Column('evidence_type', sa.String(length=30), nullable=False),
    sa.Column('title', sa.String(length=300), nullable=True),
    sa.Column('content', sa.Text(), nullable=True),
    sa.Column('url', sa.Text(), nullable=True),
    sa.Column('content_hash', sa.String(length=64), nullable=True),
    sa.Column('relation', sa.String(length=30), nullable=False),
    sa.Column('relevance_score', sa.Float(), nullable=True),
    sa.Column('reliability_score', sa.Float(), nullable=True),
    sa.Column('temporal_match', sa.Float(), nullable=True),
    sa.Column('geographic_match', sa.Float(), nullable=True),
    sa.Column('observed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('retrieved_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('location_text', sa.String(length=300), nullable=True),
    sa.Column('latitude', sa.Float(), nullable=True),
    sa.Column('longitude', sa.Float(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.CheckConstraint("evidence_type IN ('bulletin', 'news_article', 'sensor_reading', 'dataset_record', 'social_post', 'other')", name=op.f('ck_evidence_evidence_type_valid')),
    sa.CheckConstraint("relation IN ('supports', 'contradicts', 'partially_supports', 'unrelated')", name=op.f('ck_evidence_evidence_relation_valid')),
    sa.CheckConstraint('geographic_match IS NULL OR (geographic_match BETWEEN 0.0 AND 1.0)', name=op.f('ck_evidence_evidence_geographic_range')),
    sa.CheckConstraint('relevance_score IS NULL OR (relevance_score BETWEEN 0.0 AND 1.0)', name=op.f('ck_evidence_evidence_relevance_range')),
    sa.CheckConstraint('temporal_match IS NULL OR (temporal_match BETWEEN 0.0 AND 1.0)', name=op.f('ck_evidence_evidence_temporal_range')),
    sa.ForeignKeyConstraint(['claim_id'], ['claims.id'], name=op.f('fk_evidence_claim_id_claims'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['source_id'], ['sources.id'], name=op.f('fk_evidence_source_id_sources'), ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_evidence')),
    sa.UniqueConstraint('claim_id', 'source_id', 'content_hash', name='uq_evidence_claim_source_hash')
    )
    op.create_index(op.f('ix_evidence_claim_id'), 'evidence', ['claim_id'], unique=False)
    op.create_index(op.f('ix_evidence_content_hash'), 'evidence', ['content_hash'], unique=False)
    op.create_index(op.f('ix_evidence_observed_at'), 'evidence', ['observed_at'], unique=False)
    op.create_index(op.f('ix_evidence_source_id'), 'evidence', ['source_id'], unique=False)
    op.create_table('posts',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('source_id', sa.Integer(), nullable=False),
    sa.Column('event_id', sa.Integer(), nullable=True),
    sa.Column('external_id', sa.String(length=200), nullable=True),
    sa.Column('text', sa.Text(), nullable=False),
    sa.Column('content_hash', sa.String(length=64), nullable=False),
    sa.Column('language', sa.String(length=10), nullable=True),
    sa.Column('media_reference', sa.Text(), nullable=True),
    sa.Column('author_hash', sa.String(length=64), nullable=True),
    sa.Column('published_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('ingested_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('location_text', sa.String(length=300), nullable=True),
    sa.Column('admin_district', sa.String(length=120), nullable=True),
    sa.Column('latitude', sa.Float(), nullable=True),
    sa.Column('longitude', sa.Float(), nullable=True),
    sa.Column('geo_confidence', sa.Float(), nullable=True),
    sa.Column('engagement', sa.JSON(), nullable=True),
    sa.Column('raw_payload', sa.JSON(), nullable=True),
    sa.Column('ingestion_status', sa.String(length=20), nullable=False),
    sa.Column('ingestion_error', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.CheckConstraint("ingestion_status IN ('pending', 'normalized', 'processed', 'failed', 'skipped')", name=op.f('ck_posts_post_ingestion_status_valid')),
    sa.ForeignKeyConstraint(['event_id'], ['events.id'], name=op.f('fk_posts_event_id_events'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['source_id'], ['sources.id'], name=op.f('fk_posts_source_id_sources'), ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_posts'))
    )
    op.create_index(op.f('ix_posts_admin_district'), 'posts', ['admin_district'], unique=False)
    op.create_index(op.f('ix_posts_author_hash'), 'posts', ['author_hash'], unique=False)
    op.create_index(op.f('ix_posts_content_hash'), 'posts', ['content_hash'], unique=True)
    op.create_index(op.f('ix_posts_event_id'), 'posts', ['event_id'], unique=False)
    op.create_index(op.f('ix_posts_external_id'), 'posts', ['external_id'], unique=False)
    op.create_index(op.f('ix_posts_ingestion_status'), 'posts', ['ingestion_status'], unique=False)
    op.create_index(op.f('ix_posts_published_at'), 'posts', ['published_at'], unique=False)
    op.create_index(op.f('ix_posts_source_id'), 'posts', ['source_id'], unique=False)
    op.create_table('risk_assessments',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('claim_id', sa.Integer(), nullable=False),
    sa.Column('information_risk', sa.String(length=20), nullable=False),
    sa.Column('information_risk_score', sa.Float(), nullable=True),
    sa.Column('potential_impact', sa.String(length=20), nullable=False),
    sa.Column('potential_impact_score', sa.Float(), nullable=True),
    sa.Column('propagation_score', sa.Float(), nullable=True),
    sa.Column('priority', sa.Float(), nullable=True),
    sa.Column('formula_version', sa.String(length=50), nullable=False),
    sa.Column('explanation', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.CheckConstraint("information_risk IN ('low', 'medium', 'high', 'critical')", name=op.f('ck_risk_assessments_ra_information_risk_valid')),
    sa.CheckConstraint("potential_impact IN ('low', 'medium', 'high', 'critical')", name=op.f('ck_risk_assessments_ra_potential_impact_valid')),
    sa.ForeignKeyConstraint(['claim_id'], ['claims.id'], name=op.f('fk_risk_assessments_claim_id_claims'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_risk_assessments'))
    )
    op.create_index(op.f('ix_risk_assessments_claim_id'), 'risk_assessments', ['claim_id'], unique=False)
    op.create_index(op.f('ix_risk_assessments_priority'), 'risk_assessments', ['priority'], unique=False)
    op.create_table('sensor_events',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('event_id', sa.Integer(), nullable=True),
    sa.Column('source_id', sa.Integer(), nullable=True),
    sa.Column('sensor_id', sa.String(length=100), nullable=False),
    sa.Column('sensor_type', sa.String(length=30), nullable=False),
    sa.Column('value', sa.Float(), nullable=False),
    sa.Column('unit', sa.String(length=20), nullable=False),
    sa.Column('quality_flag', sa.String(length=20), nullable=False),
    sa.Column('observed_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('location_text', sa.String(length=300), nullable=True),
    sa.Column('admin_district', sa.String(length=120), nullable=True),
    sa.Column('latitude', sa.Float(), nullable=True),
    sa.Column('longitude', sa.Float(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.CheckConstraint("quality_flag IN ('ok', 'suspect', 'missing', 'calibrating')", name=op.f('ck_sensor_events_sensor_quality_flag_valid')),
    sa.CheckConstraint("sensor_type IN ('rainfall', 'water_level', 'soil_moisture', 'tilt', 'temperature', 'other')", name=op.f('ck_sensor_events_sensor_type_valid')),
    sa.ForeignKeyConstraint(['event_id'], ['events.id'], name=op.f('fk_sensor_events_event_id_events'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['source_id'], ['sources.id'], name=op.f('fk_sensor_events_source_id_sources'), ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_sensor_events'))
    )
    op.create_index(op.f('ix_sensor_events_admin_district'), 'sensor_events', ['admin_district'], unique=False)
    op.create_index(op.f('ix_sensor_events_event_id'), 'sensor_events', ['event_id'], unique=False)
    op.create_index(op.f('ix_sensor_events_observed_at'), 'sensor_events', ['observed_at'], unique=False)
    op.create_index(op.f('ix_sensor_events_sensor_id'), 'sensor_events', ['sensor_id'], unique=False)
    op.create_index(op.f('ix_sensor_events_sensor_type'), 'sensor_events', ['sensor_type'], unique=False)
    op.create_index(op.f('ix_sensor_events_source_id'), 'sensor_events', ['source_id'], unique=False)
    op.create_table('test_results',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('participant_id', sa.String(length=64), nullable=False),
    sa.Column('intervention_id', sa.Integer(), nullable=True),
    sa.Column('phase', sa.String(length=20), nullable=False),
    sa.Column('answer', sa.String(length=300), nullable=True),
    sa.Column('is_correct', sa.Boolean(), nullable=True),
    sa.Column('self_confidence', sa.Float(), nullable=True),
    sa.Column('response_time_ms', sa.Float(), nullable=True),
    sa.Column('answered_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.CheckConstraint("phase IN ('pre', 'post', 'followup')", name=op.f('ck_test_results_test_result_phase_valid')),
    sa.CheckConstraint('self_confidence IS NULL OR (self_confidence BETWEEN 0.0 AND 1.0)', name=op.f('ck_test_results_test_result_confidence_range')),
    sa.ForeignKeyConstraint(['intervention_id'], ['interventions.id'], name=op.f('fk_test_results_intervention_id_interventions'), ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_test_results'))
    )
    op.create_index(op.f('ix_test_results_intervention_id'), 'test_results', ['intervention_id'], unique=False)
    op.create_index(op.f('ix_test_results_participant_id'), 'test_results', ['participant_id'], unique=False)
    op.create_index(op.f('ix_test_results_phase'), 'test_results', ['phase'], unique=False)
    op.create_table('model_predictions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('claim_id', sa.Integer(), nullable=True),
    sa.Column('post_id', sa.Integer(), nullable=True),
    sa.Column('task', sa.String(length=50), nullable=False),
    sa.Column('model_name', sa.String(length=100), nullable=False),
    sa.Column('model_version', sa.String(length=50), nullable=False),
    sa.Column('output', sa.JSON(), nullable=False),
    sa.Column('confidence', sa.Float(), nullable=True),
    sa.Column('input_hash', sa.String(length=64), nullable=True),
    sa.Column('latency_ms', sa.Float(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['claim_id'], ['claims.id'], name=op.f('fk_model_predictions_claim_id_claims'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['post_id'], ['posts.id'], name=op.f('fk_model_predictions_post_id_posts'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_model_predictions'))
    )
    op.create_index(op.f('ix_model_predictions_claim_id'), 'model_predictions', ['claim_id'], unique=False)
    op.create_index(op.f('ix_model_predictions_input_hash'), 'model_predictions', ['input_hash'], unique=False)
    op.create_index(op.f('ix_model_predictions_model_version'), 'model_predictions', ['model_version'], unique=False)
    op.create_index(op.f('ix_model_predictions_post_id'), 'model_predictions', ['post_id'], unique=False)
    op.create_index(op.f('ix_model_predictions_task'), 'model_predictions', ['task'], unique=False)
    op.add_column('claims', sa.Column('post_id', sa.Integer(), nullable=True))
    op.add_column('claims', sa.Column('cluster_id', sa.Integer(), nullable=True))
    op.create_index(op.f('ix_claims_cluster_id'), 'claims', ['cluster_id'], unique=False)
    op.create_index(op.f('ix_claims_post_id'), 'claims', ['post_id'], unique=False)
    op.create_foreign_key(op.f('fk_claims_post_id_posts'), 'claims', 'posts', ['post_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key(op.f('fk_claims_cluster_id_claim_clusters'), 'claims', 'claim_clusters', ['cluster_id'], ['id'], ondelete='SET NULL')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('fk_claims_cluster_id_claim_clusters'), 'claims', type_='foreignkey')
    op.drop_constraint(op.f('fk_claims_post_id_posts'), 'claims', type_='foreignkey')
    op.drop_index(op.f('ix_claims_post_id'), table_name='claims')
    op.drop_index(op.f('ix_claims_cluster_id'), table_name='claims')
    op.drop_column('claims', 'cluster_id')
    op.drop_column('claims', 'post_id')
    op.drop_index(op.f('ix_model_predictions_task'), table_name='model_predictions')
    op.drop_index(op.f('ix_model_predictions_post_id'), table_name='model_predictions')
    op.drop_index(op.f('ix_model_predictions_model_version'), table_name='model_predictions')
    op.drop_index(op.f('ix_model_predictions_input_hash'), table_name='model_predictions')
    op.drop_index(op.f('ix_model_predictions_claim_id'), table_name='model_predictions')
    op.drop_table('model_predictions')
    op.drop_index(op.f('ix_test_results_phase'), table_name='test_results')
    op.drop_index(op.f('ix_test_results_participant_id'), table_name='test_results')
    op.drop_index(op.f('ix_test_results_intervention_id'), table_name='test_results')
    op.drop_table('test_results')
    op.drop_index(op.f('ix_sensor_events_source_id'), table_name='sensor_events')
    op.drop_index(op.f('ix_sensor_events_sensor_type'), table_name='sensor_events')
    op.drop_index(op.f('ix_sensor_events_sensor_id'), table_name='sensor_events')
    op.drop_index(op.f('ix_sensor_events_observed_at'), table_name='sensor_events')
    op.drop_index(op.f('ix_sensor_events_event_id'), table_name='sensor_events')
    op.drop_index(op.f('ix_sensor_events_admin_district'), table_name='sensor_events')
    op.drop_table('sensor_events')
    op.drop_index(op.f('ix_risk_assessments_priority'), table_name='risk_assessments')
    op.drop_index(op.f('ix_risk_assessments_claim_id'), table_name='risk_assessments')
    op.drop_table('risk_assessments')
    op.drop_index(op.f('ix_posts_source_id'), table_name='posts')
    op.drop_index(op.f('ix_posts_published_at'), table_name='posts')
    op.drop_index(op.f('ix_posts_ingestion_status'), table_name='posts')
    op.drop_index(op.f('ix_posts_external_id'), table_name='posts')
    op.drop_index(op.f('ix_posts_event_id'), table_name='posts')
    op.drop_index(op.f('ix_posts_content_hash'), table_name='posts')
    op.drop_index(op.f('ix_posts_author_hash'), table_name='posts')
    op.drop_index(op.f('ix_posts_admin_district'), table_name='posts')
    op.drop_table('posts')
    op.drop_index(op.f('ix_evidence_source_id'), table_name='evidence')
    op.drop_index(op.f('ix_evidence_observed_at'), table_name='evidence')
    op.drop_index(op.f('ix_evidence_content_hash'), table_name='evidence')
    op.drop_index(op.f('ix_evidence_claim_id'), table_name='evidence')
    op.drop_table('evidence')
    op.drop_index(op.f('ix_interventions_target_signal'), table_name='interventions')
    op.drop_index(op.f('ix_interventions_intervention_type'), table_name='interventions')
    op.drop_table('interventions')
    op.drop_table('claim_clusters')
    # ### end Alembic commands ###
