"""initial core tables

Revision ID: 85e2e648d7e8
Revises: 
Create Date: 2026-09-02 21:42:35.587148

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '85e2e648d7e8'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('events',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('event_type', sa.String(length=30), nullable=False),
    sa.Column('title', sa.String(length=300), nullable=False),
    sa.Column('summary', sa.Text(), nullable=True),
    sa.Column('location_text', sa.String(length=300), nullable=True),
    sa.Column('admin_district', sa.String(length=120), nullable=True),
    sa.Column('latitude', sa.Float(), nullable=True),
    sa.Column('longitude', sa.Float(), nullable=True),
    sa.Column('geo_confidence', sa.Float(), nullable=True),
    sa.Column('start_time', sa.DateTime(timezone=True), nullable=False),
    sa.Column('end_time', sa.DateTime(timezone=True), nullable=True),
    sa.Column('severity', sa.String(length=20), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.CheckConstraint("event_type IN ('flood', 'landslide', 'earthquake', 'cyclone', 'fire', 'other')", name=op.f('ck_events_event_type_valid')),
    sa.CheckConstraint("severity IN ('low', 'medium', 'high', 'critical')", name=op.f('ck_events_event_severity_valid')),
    sa.CheckConstraint("status IN ('developing', 'monitoring', 'stable', 'resolved')", name=op.f('ck_events_event_status_valid')),
    sa.CheckConstraint('latitude IS NULL OR (latitude BETWEEN -90 AND 90)', name=op.f('ck_events_event_lat_range')),
    sa.CheckConstraint('longitude IS NULL OR (longitude BETWEEN -180 AND 180)', name=op.f('ck_events_event_lon_range')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_events'))
    )
    op.create_index(op.f('ix_events_admin_district'), 'events', ['admin_district'], unique=False)
    op.create_index(op.f('ix_events_event_type'), 'events', ['event_type'], unique=False)
    op.create_index(op.f('ix_events_start_time'), 'events', ['start_time'], unique=False)
    op.create_index(op.f('ix_events_status'), 'events', ['status'], unique=False)
    op.create_table('sources',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('source_type', sa.String(length=20), nullable=False),
    sa.Column('url', sa.Text(), nullable=True),
    sa.Column('reliability_tier', sa.String(length=20), nullable=False),
    sa.Column('reliability_score', sa.Float(), nullable=False),
    sa.Column('rationale', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.CheckConstraint("reliability_tier IN ('very_high', 'high', 'medium', 'low', 'very_low', 'unknown')", name=op.f('ck_sources_reliability_tier_valid')),
    sa.CheckConstraint("source_type IN ('official', 'news', 'social', 'sensor', 'dataset')", name=op.f('ck_sources_source_type_valid')),
    sa.CheckConstraint('reliability_score >= 0.0 AND reliability_score <= 1.0', name=op.f('ck_sources_reliability_score_range')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_sources')),
    sa.UniqueConstraint('name', name=op.f('uq_sources_name'))
    )
    op.create_index(op.f('ix_sources_source_type'), 'sources', ['source_type'], unique=False)
    op.create_table('claims',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('event_id', sa.Integer(), nullable=True),
    sa.Column('claim_text', sa.Text(), nullable=False),
    sa.Column('claim_type', sa.String(length=40), nullable=False),
    sa.Column('disaster_type', sa.String(length=30), nullable=False),
    sa.Column('location_text', sa.String(length=300), nullable=True),
    sa.Column('admin_district', sa.String(length=120), nullable=True),
    sa.Column('latitude', sa.Float(), nullable=True),
    sa.Column('longitude', sa.Float(), nullable=True),
    sa.Column('geo_confidence', sa.Float(), nullable=True),
    sa.Column('event_time', sa.DateTime(timezone=True), nullable=True),
    sa.Column('time_precision', sa.String(length=20), nullable=False),
    sa.Column('verification_status', sa.String(length=30), nullable=False),
    sa.Column('confidence', sa.Float(), nullable=True),
    sa.Column('confidence_low', sa.Float(), nullable=True),
    sa.Column('confidence_high', sa.Float(), nullable=True),
    sa.Column('information_risk', sa.String(length=20), nullable=True),
    sa.Column('potential_impact', sa.String(length=20), nullable=True),
    sa.Column('model_version', sa.String(length=50), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.CheckConstraint("claim_type IN ('road_blockage', 'flood_level', 'water_level', 'infrastructure_damage', 'casualty', 'weather', 'official_announcement', 'evacuation', 'other')", name=op.f('ck_claims_claim_type_valid')),
    sa.CheckConstraint("disaster_type IN ('flood', 'landslide', 'earthquake', 'cyclone', 'fire', 'other', 'none')", name=op.f('ck_claims_claim_disaster_type_valid')),
    sa.CheckConstraint("information_risk IS NULL OR information_risk IN ('low', 'medium', 'high', 'critical')", name=op.f('ck_claims_claim_information_risk_valid')),
    sa.CheckConstraint("potential_impact IS NULL OR potential_impact IN ('low', 'medium', 'high', 'critical')", name=op.f('ck_claims_claim_potential_impact_valid')),
    sa.CheckConstraint("time_precision IN ('exact', 'hour', 'day', 'month', 'unknown')", name=op.f('ck_claims_claim_time_precision_valid')),
    sa.CheckConstraint("verification_status IN ('supported', 'contradicted', 'needs_verification', 'insufficient_evidence')", name=op.f('ck_claims_claim_verification_status_valid')),
    sa.CheckConstraint('confidence IS NULL OR (confidence BETWEEN 0.0 AND 1.0)', name=op.f('ck_claims_claim_confidence_range')),
    sa.ForeignKeyConstraint(['event_id'], ['events.id'], name=op.f('fk_claims_event_id_events'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_claims'))
    )
    op.create_index(op.f('ix_claims_admin_district'), 'claims', ['admin_district'], unique=False)
    op.create_index(op.f('ix_claims_event_id'), 'claims', ['event_id'], unique=False)
    op.create_index(op.f('ix_claims_event_time'), 'claims', ['event_time'], unique=False)
    op.create_index(op.f('ix_claims_verification_status'), 'claims', ['verification_status'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_claims_verification_status'), table_name='claims')
    op.drop_index(op.f('ix_claims_event_time'), table_name='claims')
    op.drop_index(op.f('ix_claims_event_id'), table_name='claims')
    op.drop_index(op.f('ix_claims_admin_district'), table_name='claims')
    op.drop_table('claims')
    op.drop_index(op.f('ix_sources_source_type'), table_name='sources')
    op.drop_table('sources')
    op.drop_index(op.f('ix_events_status'), table_name='events')
    op.drop_index(op.f('ix_events_start_time'), table_name='events')
    op.drop_index(op.f('ix_events_event_type'), table_name='events')
    op.drop_index(op.f('ix_events_admin_district'), table_name='events')
    op.drop_table('events')
    # ### end Alembic commands ###
