"""initial schema

Revision ID: ca57add69d1b
Revises: 
Create Date: 2026-09-05 22:50:04.419797

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ca57add69d1b'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('claim_clusters',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('label', sa.String(length=300), nullable=True),
    sa.Column('summary', sa.Text(), nullable=True),
    sa.Column('representative_claim_id', sa.Integer(), nullable=True),
    sa.Column('size', sa.Integer(), nullable=False),
    sa.Column('cohesion', sa.Float(), nullable=True),
    sa.Column('method_version', sa.String(length=50), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['representative_claim_id'], ['claims.id'], name=op.f('fk_claim_clusters_representative_claim_id_claims'), ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_claim_clusters'))
    )
    op.create_table('claims',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('event_id', sa.Integer(), nullable=True),
    sa.Column('post_id', sa.Integer(), nullable=True),
    sa.Column('cluster_id', sa.Integer(), nullable=True),
    sa.Column('claim_text', sa.Text(), nullable=False),
    sa.Column('claim_type', sa.String(length=40), nullable=False),
    sa.Column('disaster_type', sa.String(length=30), nullable=False),
    sa.Column('location_text', sa.String(length=300), nullable=True),
    sa.Column('admin_district', sa.String(length=120), nullable=True),
    sa.Column('latitude', sa.Float(), nullable=True),
    sa.Column('longitude', sa.Float(), nullable=True),
    sa.Column('geo_confidence', sa.Float(), nullable=True),
    sa.Column('event_time', sa.DateTime(timezone=True), nullable=True),
    sa.Column('last_verified_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('time_precision', sa.String(length=20), nullable=False),
    sa.Column('verification_status', sa.String(length=30), nullable=False),
    sa.Column('confidence', sa.Float(), nullable=True),
    sa.Column('confidence_low', sa.Float(), nullable=True),
    sa.Column('confidence_high', sa.Float(), nullable=True),
    sa.Column('information_risk', sa.String(length=20), nullable=True),
    sa.Column('potential_impact', sa.String(length=20), nullable=True),
    sa.Column('model_version', sa.String(length=50), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.CheckConstraint("claim_type IN ('road_blockage', 'flood_level', 'water_level', 'infrastructure_damage', 'casualty', 'weather', 'official_announcement', 'evacuation', 'other')", name=op.f('ck_claims_claim_type_valid')),
    sa.CheckConstraint("disaster_type IN ('flood', 'landslide', 'earthquake', 'cyclone', 'fire', 'other', 'none')", name=op.f('ck_claims_claim_disaster_type_valid')),
    sa.CheckConstraint("information_risk IS NULL OR information_risk IN ('low', 'medium', 'high', 'critical')", name=op.f('ck_claims_claim_information_risk_valid')),
    sa.CheckConstraint("potential_impact IS NULL OR potential_impact IN ('low', 'medium', 'high', 'critical')", name=op.f('ck_claims_claim_potential_impact_valid')),
    sa.CheckConstraint("time_precision IN ('exact', 'hour', 'day', 'month', 'unknown')", name=op.f('ck_claims_claim_time_precision_valid')),
    sa.CheckConstraint("verification_status IN ('supported', 'contradicted', 'needs_verification', 'insufficient_evidence')", name=op.f('ck_claims_claim_verification_status_valid')),
    sa.CheckConstraint('confidence IS NULL OR (confidence BETWEEN 0.0 AND 1.0)', name=op.f('ck_claims_claim_confidence_range')),
    sa.ForeignKeyConstraint(['cluster_id'], ['claim_clusters.id'], name=op.f('fk_claims_cluster_id_claim_clusters'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['event_id'], ['events.id'], name=op.f('fk_claims_event_id_events'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['post_id'], ['posts.id'], name=op.f('fk_claims_post_id_posts'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_claims'))
    )
    with op.batch_alter_table('claims', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_claims_admin_district'), ['admin_district'], unique=False)
        batch_op.create_index(batch_op.f('ix_claims_cluster_id'), ['cluster_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_claims_event_id'), ['event_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_claims_event_time'), ['event_time'], unique=False)
        batch_op.create_index(batch_op.f('ix_claims_last_verified_at'), ['last_verified_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_claims_post_id'), ['post_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_claims_verification_status'), ['verification_status'], unique=False)

    op.create_table('events',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('event_type', sa.String(length=30), nullable=False),
    sa.Column('title', sa.String(length=300), nullable=False),
    sa.Column('summary', sa.Text(), nullable=True),
    sa.Column('location_text', sa.String(length=300), nullable=True),
    sa.Column('admin_district', sa.String(length=120), nullable=True),
    sa.Column('latitude', sa.Float(), nullable=True),
    sa.Column('longitude', sa.Float(), nullable=True),
    sa.Column('geo_confidence', sa.Float(), nullable=True),
    sa.Column('start_time', sa.DateTime(timezone=True), nullable=False),
    sa.Column('end_time', sa.DateTime(timezone=True), nullable=True),
    sa.Column('severity', sa.String(length=20), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.CheckConstraint("event_type IN ('flood', 'landslide', 'earthquake', 'cyclone', 'fire', 'other')", name=op.f('ck_events_event_type_valid')),
    sa.CheckConstraint("severity IN ('low', 'medium', 'high', 'critical')", name=op.f('ck_events_event_severity_valid')),
    sa.CheckConstraint("status IN ('developing', 'monitoring', 'stable', 'resolved')", name=op.f('ck_events_event_status_valid')),
    sa.CheckConstraint('latitude IS NULL OR (latitude BETWEEN -90 AND 90)', name=op.f('ck_events_event_lat_range')),
    sa.CheckConstraint('longitude IS NULL OR (longitude BETWEEN -180 AND 180)', name=op.f('ck_events_event_lon_range')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_events'))
    )
    with op.batch_alter_table('events', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_events_admin_district'), ['admin_district'], unique=False)
        batch_op.create_index(batch_op.f('ix_events_event_type'), ['event_type'], unique=False)
        batch_op.create_index(batch_op.f('ix_events_start_time'), ['start_time'], unique=False)
        batch_op.create_index(batch_op.f('ix_events_status'), ['status'], unique=False)

    op.create_table('interventions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=300), nullable=False),
    sa.Column('intervention_type', sa.String(length=30), nullable=False),
    sa.Column('body', sa.Text(), nullable=True),
    sa.Column('example', sa.Text(), nullable=True),
    sa.Column('question', sa.Text(), nullable=True),
    sa.Column('options', sa.JSON(), nullable=True),
    sa.Column('answer_explanation', sa.Text(), nullable=True),
    sa.Column('target_signal', sa.String(length=100), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.CheckConstraint("intervention_type IN ('prebunk', 'explanation', 'technique_warning', 'quiz')", name=op.f('ck_interventions_intervention_type_valid')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_interventions'))
    )
    with op.batch_alter_table('interventions', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_interventions_intervention_type'), ['intervention_type'], unique=False)
        batch_op.create_index(batch_op.f('ix_interventions_target_signal'), ['target_signal'], unique=False)

    op.create_table('sources',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('source_type', sa.String(length=20), nullable=False),
    sa.Column('url', sa.Text(), nullable=True),
    sa.Column('reliability_tier', sa.String(length=20), nullable=False),
    sa.Column('reliability_score', sa.Float(), nullable=False),
    sa.Column('rationale', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.CheckConstraint("reliability_tier IN ('very_high', 'high', 'medium', 'low', 'very_low', 'unknown')", name=op.f('ck_sources_reliability_tier_valid')),
    sa.CheckConstraint("source_type IN ('official', 'news', 'social', 'sensor', 'dataset')", name=op.f('ck_sources_source_type_valid')),
    sa.CheckConstraint('reliability_score >= 0.0 AND reliability_score <= 1.0', name=op.f('ck_sources_reliability_score_range')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_sources')),
    sa.UniqueConstraint('name', name=op.f('uq_sources_name'))
    )
    with op.batch_alter_table('sources', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_sources_source_type'), ['source_type'], unique=False)

    op.create_table('claim_reasons',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('claim_id', sa.Integer(), nullable=False),
    sa.Column('text', sa.Text(), nullable=False),
    sa.Column('reason_kind', sa.String(length=30), nullable=False),
    sa.Column('position', sa.Integer(), nullable=False),
    sa.Column('generated_by', sa.String(length=50), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.CheckConstraint("reason_kind IN ('evidence_support', 'evidence_absence', 'evidence_conflict', 'source_reliability', 'temporal', 'geographic', 'linguistic', 'propagation', 'other')", name=op.f('ck_claim_reasons_claim_reason_kind_valid')),
    sa.ForeignKeyConstraint(['claim_id'], ['claims.id'], name=op.f('fk_claim_reasons_claim_id_claims'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_claim_reasons'))
    )
    with op.batch_alter_table('claim_reasons', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_claim_reasons_claim_id'), ['claim_id'], unique=False)

    op.create_table('event_timeline',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('event_id', sa.Integer(), nullable=False),
    sa.Column('occurred_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('label', sa.String(length=300), nullable=False),
    sa.Column('kind', sa.String(length=20), nullable=False),
    sa.Column('detail', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.CheckConstraint("kind IN ('info', 'warn', 'alert', 'official')", name=op.f('ck_event_timeline_timeline_kind_valid')),
    sa.ForeignKeyConstraint(['event_id'], ['events.id'], name=op.f('fk_event_timeline_event_id_events'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_event_timeline'))
    )
    with op.batch_alter_table('event_timeline', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_event_timeline_event_id'), ['event_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_event_timeline_occurred_at'), ['occurred_at'], unique=False)

    op.create_table('evidence',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('claim_id', sa.Integer(), nullable=False),
    sa.Column('source_id', sa.Integer(), nullable=False),
    sa.Column('evidence_type', sa.String(length=30), nullable=False),
    sa.Column('title', sa.String(length=300), nullable=True),
    sa.Column('content', sa.Text(), nullable=True),
    sa.Column('url', sa.Text(), nullable=True),
    sa.Column('content_hash', sa.String(length=64), nullable=True),
    sa.Column('derived_from_evidence_id', sa.Integer(), nullable=True),
    sa.Column('relation', sa.String(length=30), nullable=False),
    sa.Column('relevance_score', sa.Float(), nullable=True),
    sa.Column('reliability_score', sa.Float(), nullable=True),
    sa.Column('temporal_match', sa.Float(), nullable=True),
    sa.Column('geographic_match', sa.Float(), nullable=True),
    sa.Column('observed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('retrieved_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('location_text', sa.String(length=300), nullable=True),
    sa.Column('latitude', sa.Float(), nullable=True),
    sa.Column('longitude', sa.Float(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.CheckConstraint("evidence_type IN ('bulletin', 'news_article', 'sensor_reading', 'dataset_record', 'social_post', 'other')", name=op.f('ck_evidence_evidence_type_valid')),
    sa.CheckConstraint("relation IN ('supports', 'contradicts', 'partially_supports', 'unrelated')", name=op.f('ck_evidence_evidence_relation_valid')),
    sa.CheckConstraint('geographic_match IS NULL OR (geographic_match BETWEEN 0.0 AND 1.0)', name=op.f('ck_evidence_evidence_geographic_range')),
    sa.CheckConstraint('relevance_score IS NULL OR (relevance_score BETWEEN 0.0 AND 1.0)', name=op.f('ck_evidence_evidence_relevance_range')),
    sa.CheckConstraint('temporal_match IS NULL OR (temporal_match BETWEEN 0.0 AND 1.0)', name=op.f('ck_evidence_evidence_temporal_range')),
    sa.ForeignKeyConstraint(['claim_id'], ['claims.id'], name=op.f('fk_evidence_claim_id_claims'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['derived_from_evidence_id'], ['evidence.id'], name=op.f('fk_evidence_derived_from_evidence_id_evidence'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['source_id'], ['sources.id'], name=op.f('fk_evidence_source_id_sources'), ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_evidence')),
    sa.UniqueConstraint('claim_id', 'source_id', 'content_hash', name='uq_evidence_claim_source_hash')
    )
    with op.batch_alter_table('evidence', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_evidence_claim_id'), ['claim_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_evidence_content_hash'), ['content_hash'], unique=False)
        batch_op.create_index(batch_op.f('ix_evidence_derived_from_evidence_id'), ['derived_from_evidence_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_evidence_observed_at'), ['observed_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_evidence_source_id'), ['source_id'], unique=False)

    op.create_table('manipulation_signals',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('claim_id', sa.Integer(), nullable=False),
    sa.Column('signal_type', sa.String(length=40), nullable=False),
    sa.Column('value', sa.Float(), nullable=False),
    sa.Column('note', sa.Text(), nullable=True),
    sa.Column('method_version', sa.String(length=50), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.CheckConstraint("signal_type IN ('artificial_urgency', 'fake_authority', 'emotional_language', 'evidence_conflict', 'context_inconsistency', 'repeated_wording', 'missing_attribution', 'engagement_anomaly')", name=op.f('ck_manipulation_signals_signal_type_valid')),
    sa.CheckConstraint('value BETWEEN 0.0 AND 1.0', name=op.f('ck_manipulation_signals_signal_value_range')),
    sa.ForeignKeyConstraint(['claim_id'], ['claims.id'], name=op.f('fk_manipulation_signals_claim_id_claims'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_manipulation_signals'))
    )
    with op.batch_alter_table('manipulation_signals', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_manipulation_signals_claim_id'), ['claim_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_manipulation_signals_signal_type'), ['signal_type'], unique=False)

    op.create_table('posts',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('source_id', sa.Integer(), nullable=False),
    sa.Column('event_id', sa.Integer(), nullable=True),
    sa.Column('external_id', sa.String(length=200), nullable=True),
    sa.Column('text', sa.Text(), nullable=False),
    sa.Column('content_hash', sa.String(length=64), nullable=False),
    sa.Column('language', sa.String(length=10), nullable=True),
    sa.Column('media_reference', sa.Text(), nullable=True),
    sa.Column('author_hash', sa.String(length=64), nullable=True),
    sa.Column('published_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('ingested_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('location_text', sa.String(length=300), nullable=True),
    sa.Column('admin_district', sa.String(length=120), nullable=True),
    sa.Column('latitude', sa.Float(), nullable=True),
    sa.Column('longitude', sa.Float(), nullable=True),
    sa.Column('geo_confidence', sa.Float(), nullable=True),
    sa.Column('engagement', sa.JSON(), nullable=True),
    sa.Column('raw_payload', sa.JSON(), nullable=True),
    sa.Column('ingestion_status', sa.String(length=20), nullable=False),
    sa.Column('ingestion_error', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.CheckConstraint("ingestion_status IN ('pending', 'normalized', 'processed', 'failed', 'skipped')", name=op.f('ck_posts_post_ingestion_status_valid')),
    sa.ForeignKeyConstraint(['event_id'], ['events.id'], name=op.f('fk_posts_event_id_events'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['source_id'], ['sources.id'], name=op.f('fk_posts_source_id_sources'), ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_posts'))
    )
    with op.batch_alter_table('posts', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_posts_admin_district'), ['admin_district'], unique=False)
        batch_op.create_index(batch_op.f('ix_posts_author_hash'), ['author_hash'], unique=False)
        batch_op.create_index(batch_op.f('ix_posts_content_hash'), ['content_hash'], unique=True)
        batch_op.create_index(batch_op.f('ix_posts_event_id'), ['event_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_posts_external_id'), ['external_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_posts_ingestion_status'), ['ingestion_status'], unique=False)
        batch_op.create_index(batch_op.f('ix_posts_published_at'), ['published_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_posts_source_id'), ['source_id'], unique=False)

    op.create_table('risk_assessments',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('claim_id', sa.Integer(), nullable=False),
    sa.Column('information_risk', sa.String(length=20), nullable=False),
    sa.Column('information_risk_score', sa.Float(), nullable=True),
    sa.Column('potential_impact', sa.String(length=20), nullable=False),
    sa.Column('potential_impact_score', sa.Float(), nullable=True),
    sa.Column('propagation_score', sa.Float(), nullable=True),
    sa.Column('priority', sa.Float(), nullable=True),
    sa.Column('formula_version', sa.String(length=50), nullable=False),
    sa.Column('explanation', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.CheckConstraint("information_risk IN ('low', 'medium', 'high', 'critical')", name=op.f('ck_risk_assessments_ra_information_risk_valid')),
    sa.CheckConstraint("potential_impact IN ('low', 'medium', 'high', 'critical')", name=op.f('ck_risk_assessments_ra_potential_impact_valid')),
    sa.ForeignKeyConstraint(['claim_id'], ['claims.id'], name=op.f('fk_risk_assessments_claim_id_claims'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_risk_assessments'))
    )
    with op.batch_alter_table('risk_assessments', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_risk_assessments_claim_id'), ['claim_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_risk_assessments_priority'), ['priority'], unique=False)

    op.create_table('sensor_events',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('event_id', sa.Integer(), nullable=True),
    sa.Column('source_id', sa.Integer(), nullable=True),
    sa.Column('sensor_id', sa.String(length=100), nullable=False),
    sa.Column('sensor_type', sa.String(length=30), nullable=False),
    sa.Column('value', sa.Float(), nullable=False),
    sa.Column('unit', sa.String(length=20), nullable=False),
    sa.Column('quality_flag', sa.String(length=20), nullable=False),
    sa.Column('observed_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('location_text', sa.String(length=300), nullable=True),
    sa.Column('admin_district', sa.String(length=120), nullable=True),
    sa.Column('latitude', sa.Float(), nullable=True),
    sa.Column('longitude', sa.Float(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.CheckConstraint("quality_flag IN ('ok', 'suspect', 'missing', 'calibrating')", name=op.f('ck_sensor_events_sensor_quality_flag_valid')),
    sa.CheckConstraint("sensor_type IN ('rainfall', 'water_level', 'soil_moisture', 'tilt', 'temperature', 'other')", name=op.f('ck_sensor_events_sensor_type_valid')),
    sa.ForeignKeyConstraint(['event_id'], ['events.id'], name=op.f('fk_sensor_events_event_id_events'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['source_id'], ['sources.id'], name=op.f('fk_sensor_events_source_id_sources'), ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_sensor_events'))
    )
    with op.batch_alter_table('sensor_events', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_sensor_events_admin_district'), ['admin_district'], unique=False)
        batch_op.create_index(batch_op.f('ix_sensor_events_event_id'), ['event_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_sensor_events_observed_at'), ['observed_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_sensor_events_sensor_id'), ['sensor_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_sensor_events_sensor_type'), ['sensor_type'], unique=False)
        batch_op.create_index(batch_op.f('ix_sensor_events_source_id'), ['source_id'], unique=False)

    op.create_table('test_results',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('participant_id', sa.String(length=64), nullable=False),
    sa.Column('intervention_id', sa.Integer(), nullable=True),
    sa.Column('phase', sa.String(length=20), nullable=False),
    sa.Column('answer', sa.String(length=300), nullable=True),
    sa.Column('is_correct', sa.Boolean(), nullable=True),
    sa.Column('self_confidence', sa.Float(), nullable=True),
    sa.Column('response_time_ms', sa.Float(), nullable=True),
    sa.Column('answered_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.CheckConstraint("phase IN ('pre', 'post', 'followup')", name=op.f('ck_test_results_test_result_phase_valid')),
    sa.CheckConstraint('self_confidence IS NULL OR (self_confidence BETWEEN 0.0 AND 1.0)', name=op.f('ck_test_results_test_result_confidence_range')),
    sa.ForeignKeyConstraint(['intervention_id'], ['interventions.id'], name=op.f('fk_test_results_intervention_id_interventions'), ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_test_results'))
    )
    with op.batch_alter_table('test_results', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_test_results_intervention_id'), ['intervention_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_test_results_participant_id'), ['participant_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_test_results_phase'), ['phase'], unique=False)

    op.create_table('model_predictions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('claim_id', sa.Integer(), nullable=True),
    sa.Column('post_id', sa.Integer(), nullable=True),
    sa.Column('task', sa.String(length=50), nullable=False),
    sa.Column('model_name', sa.String(length=100), nullable=False),
    sa.Column('model_version', sa.String(length=50), nullable=False),
    sa.Column('output', sa.JSON(), nullable=False),
    sa.Column('confidence', sa.Float(), nullable=True),
    sa.Column('input_hash', sa.String(length=64), nullable=True),
    sa.Column('latency_ms', sa.Float(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['claim_id'], ['claims.id'], name=op.f('fk_model_predictions_claim_id_claims'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['post_id'], ['posts.id'], name=op.f('fk_model_predictions_post_id_posts'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_model_predictions'))
    )
    with op.batch_alter_table('model_predictions', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_model_predictions_claim_id'), ['claim_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_model_predictions_input_hash'), ['input_hash'], unique=False)
        batch_op.create_index(batch_op.f('ix_model_predictions_model_version'), ['model_version'], unique=False)
        batch_op.create_index(batch_op.f('ix_model_predictions_post_id'), ['post_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_model_predictions_task'), ['task'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('model_predictions', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_model_predictions_task'))
        batch_op.drop_index(batch_op.f('ix_model_predictions_post_id'))
        batch_op.drop_index(batch_op.f('ix_model_predictions_model_version'))
        batch_op.drop_index(batch_op.f('ix_model_predictions_input_hash'))
        batch_op.drop_index(batch_op.f('ix_model_predictions_claim_id'))

    op.drop_table('model_predictions')
    with op.batch_alter_table('test_results', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_test_results_phase'))
        batch_op.drop_index(batch_op.f('ix_test_results_participant_id'))
        batch_op.drop_index(batch_op.f('ix_test_results_intervention_id'))

    op.drop_table('test_results')
    with op.batch_alter_table('sensor_events', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_sensor_events_source_id'))
        batch_op.drop_index(batch_op.f('ix_sensor_events_sensor_type'))
        batch_op.drop_index(batch_op.f('ix_sensor_events_sensor_id'))
        batch_op.drop_index(batch_op.f('ix_sensor_events_observed_at'))
        batch_op.drop_index(batch_op.f('ix_sensor_events_event_id'))
        batch_op.drop_index(batch_op.f('ix_sensor_events_admin_district'))

    op.drop_table('sensor_events')
    with op.batch_alter_table('risk_assessments', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_risk_assessments_priority'))
        batch_op.drop_index(batch_op.f('ix_risk_assessments_claim_id'))

    op.drop_table('risk_assessments')
    with op.batch_alter_table('posts', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_posts_source_id'))
        batch_op.drop_index(batch_op.f('ix_posts_published_at'))
        batch_op.drop_index(batch_op.f('ix_posts_ingestion_status'))
        batch_op.drop_index(batch_op.f('ix_posts_external_id'))
        batch_op.drop_index(batch_op.f('ix_posts_event_id'))
        batch_op.drop_index(batch_op.f('ix_posts_content_hash'))
        batch_op.drop_index(batch_op.f('ix_posts_author_hash'))
        batch_op.drop_index(batch_op.f('ix_posts_admin_district'))

    op.drop_table('posts')
    with op.batch_alter_table('manipulation_signals', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_manipulation_signals_signal_type'))
        batch_op.drop_index(batch_op.f('ix_manipulation_signals_claim_id'))

    op.drop_table('manipulation_signals')
    with op.batch_alter_table('evidence', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_evidence_source_id'))
        batch_op.drop_index(batch_op.f('ix_evidence_observed_at'))
        batch_op.drop_index(batch_op.f('ix_evidence_derived_from_evidence_id'))
        batch_op.drop_index(batch_op.f('ix_evidence_content_hash'))
        batch_op.drop_index(batch_op.f('ix_evidence_claim_id'))

    op.drop_table('evidence')
    with op.batch_alter_table('event_timeline', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_event_timeline_occurred_at'))
        batch_op.drop_index(batch_op.f('ix_event_timeline_event_id'))

    op.drop_table('event_timeline')
    with op.batch_alter_table('claim_reasons', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_claim_reasons_claim_id'))

    op.drop_table('claim_reasons')
    with op.batch_alter_table('sources', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_sources_source_type'))

    op.drop_table('sources')
    with op.batch_alter_table('interventions', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_interventions_target_signal'))
        batch_op.drop_index(batch_op.f('ix_interventions_intervention_type'))

    op.drop_table('interventions')
    with op.batch_alter_table('events', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_events_status'))
        batch_op.drop_index(batch_op.f('ix_events_start_time'))
        batch_op.drop_index(batch_op.f('ix_events_event_type'))
        batch_op.drop_index(batch_op.f('ix_events_admin_district'))

    op.drop_table('events')
    with op.batch_alter_table('claims', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_claims_verification_status'))
        batch_op.drop_index(batch_op.f('ix_claims_post_id'))
        batch_op.drop_index(batch_op.f('ix_claims_last_verified_at'))
        batch_op.drop_index(batch_op.f('ix_claims_event_time'))
        batch_op.drop_index(batch_op.f('ix_claims_event_id'))
        batch_op.drop_index(batch_op.f('ix_claims_cluster_id'))
        batch_op.drop_index(batch_op.f('ix_claims_admin_district'))

    op.drop_table('claims')
    op.drop_table('claim_clusters')
    # ### end Alembic commands ###
